default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  pool: 5

development:
  primary:
    <<: *default
    database: <%= ENV['PET_DB_NAME'] %>

  followers:
    <<: *default
    database: <%= ENV['FOLLOW_DB_NAME'] %>