inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/*'

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'



